name: Build & Deploy Estructura API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy Estructura API
    runs-on: ubuntu-latest
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:latest
        # Provide the password for postgres
        env:
          POSTGRES_USER: estructura
          POSTGRES_PASSWORD: estructura@123
          POSTGRES_DB: estructura


        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
          cache: 'maven'

      - name: Unit Tests
        run: mvn test
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres/estructura
          SPRING_DATASOURCE_USERNAME: estructura
          SPRING_DATASOURCE_PASSWORD: estructura@123

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml